openapi: '3.1.0'
info:
   title: 'HR Payroll 360 API'
   version: '1.0.0'
   description: 'API documentation for HR Payroll 360 Application'
servers:
   - url: 'https://api.hr.inovasi360.id'
     description: 'Development server'
   - url: 'http://localhost:5003'
     description: 'Local server'
components:
   securitySchemes:
      BearerAuth:
         type: apiKey
         scheme: bearer
         in: header
         name: authorization
   security:
      - BearerAuth: []
paths: {}
