services:
  api-router:
    image: alpine:latest
    command: sh -c "while true; do sleep 3600; done"
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"

        # Main router for api.karsa.site
        - "traefik.http.routers.api-main.rule=Host(`api.karsa.site`)"
        - "traefik.http.routers.api-main.entrypoints=websecure"
        - "traefik.http.routers.api-main.tls.certresolver=myresolver"
        - "traefik.http.routers.api-main.service=api-lb"

        # Load balancer that will failover from api-1 to api-2
        - "traefik.http.services.api-lb.loadbalancer.server.port=5000"
        - "traefik.http.services.api-lb.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.api-lb.loadbalancer.healthcheck.interval=5s"
        - "traefik.http.services.api-lb.loadbalancer.healthcheck.timeout=3s"

        # Define servers with proper priorities (lower number = higher priority)
        - "traefik.http.services.api-lb.loadbalancer.servers.0.url=https://api-1.karsa.site"
        - "traefik.http.services.api-lb.loadbalancer.servers.0.weight=10"
        - "traefik.http.services.api-lb.loadbalancer.servers.1.url=https://api-2.karsa.site"
        - "traefik.http.services.api-lb.loadbalancer.servers.1.weight=1"

networks:
  traefik-public:
    external: true
    name: tascrum_traefik-public