services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  auth:
    image: ghcr.io/aidinaagustin/payroll-mic-auth:latest
    build:
      context: ./auth
    environment:
      - PORT=5001
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Host(`api.karsa.site`) && PathPrefix(`/auth`)"
        - "traefik.http.routers.auth.entrypoints=websecure"
        - "traefik.http.routers.auth.tls.certresolver=myresolver"
        - "traefik.http.services.auth.loadbalancer.server.port=5001"
        - "traefik.http.routers.auth.middlewares=auth-strip"
        - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
        - "com.centurylinklabs.watchtower.enable=true"

  employee:
    image: ghcr.io/aidinaagustin/payroll-mic-employee:latest
    build:
      context: ./employee
    environment:
      - PORT=5002
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    depends_on:
      - auth
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.employee.rule=Host(`api.karsa.site`) && PathPrefix(`/employee`)"
        - "traefik.http.routers.employee.entrypoints=websecure"
        - "traefik.http.routers.employee.tls.certresolver=myresolver"
        - "traefik.http.services.employee.loadbalancer.server.port=5002"
        - "traefik.http.routers.employee.middlewares=employee-strip"
        - "traefik.http.middlewares.employee-strip.stripprefix.prefixes=/employee"
        - "com.centurylinklabs.watchtower.enable=true"

  payroll:
    image: ghcr.io/aidinaagustin/payroll-mic-payroll:latest
    build:
      context: ./payroll
    environment:
      - PORT=5003
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.payroll.rule=Host(`api.karsa.site`) && PathPrefix(`/payroll`)"
        - "traefik.http.routers.payroll.entrypoints=websecure"
        - "traefik.http.routers.payroll.tls.certresolver=myresolver"
        - "traefik.http.services.payroll.loadbalancer.server.port=5003"
        - "traefik.http.routers.payroll.middlewares=payroll-strip"
        - "traefik.http.middlewares.payroll-strip.stripprefix.prefixes=/payroll"
        - "com.centurylinklabs.watchtower.enable=true"

  gateway:
    image: ghcr.io/aidinaagustin/payroll-mic-gateway:latest
    build:
      context: ./gateway
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth:5001
      - EMPLOYEE_SERVICE_URL=http://employee:5002
      - PAYROLL_SERVICE_URL=http://payroll:5003
    depends_on:
      - auth
      - employee
      - payroll
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=Host(`api.karsa.site`)"
        - "traefik.http.routers.gateway.entrypoints=websecure"
        - "traefik.http.routers.gateway.tls.certresolver=myresolver"
        - "traefik.http.services.gateway.loadbalancer.server.port=5000"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik-public:
    external: true
    name: tascrum_traefik-public