services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  auth:
    image: ghcr.io/aidinaagustin/payroll-mic-auth:latest
    build:
      context: ./auth
    environment:
      - PORT=5001
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
      - API_GROUP={{.Task.Slot}}
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth-{{.Task.Slot}}.rule=Host(`api.karsa.site`) && PathPrefix(`/auth-{{.Task.Slot}}`)"
        - "traefik.http.routers.auth-{{.Task.Slot}}.entrypoints=websecure"
        - "traefik.http.routers.auth-{{.Task.Slot}}.tls.certresolver=myresolver"
        - "traefik.http.services.auth-{{.Task.Slot}}.loadbalancer.server.port=5001"
        - "traefik.http.routers.auth-{{.Task.Slot}}.middlewares=auth-{{.Task.Slot}}-strip"
        - "traefik.http.middlewares.auth-{{.Task.Slot}}-strip.stripprefix.prefixes=/auth-{{.Task.Slot}}"
        - "com.centurylinklabs.watchtower.enable=true"
        - "api.group=api-{{.Task.Slot}}"

  employee:
    image: ghcr.io/aidinaagustin/payroll-mic-employee:latest
    build:
      context: ./employee
    environment:
      - PORT=5002
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
      - API_GROUP={{.Task.Slot}}
    depends_on:
      - auth
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.employee-{{.Task.Slot}}.rule=Host(`api.karsa.site`) && PathPrefix(`/employee-{{.Task.Slot}}`)"
        - "traefik.http.routers.employee-{{.Task.Slot}}.entrypoints=websecure"
        - "traefik.http.routers.employee-{{.Task.Slot}}.tls.certresolver=myresolver"
        - "traefik.http.services.employee-{{.Task.Slot}}.loadbalancer.server.port=5002"
        - "traefik.http.routers.employee-{{.Task.Slot}}.middlewares=employee-{{.Task.Slot}}-strip"
        - "traefik.http.middlewares.employee-{{.Task.Slot}}-strip.stripprefix.prefixes=/employee-{{.Task.Slot}}"
        - "com.centurylinklabs.watchtower.enable=true"
        - "api.group=api-{{.Task.Slot}}"

  payroll:
    image: ghcr.io/aidinaagustin/payroll-mic-payroll:latest
    build:
      context: ./payroll
    environment:
      - PORT=5003
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-l4mCps3yj578Hoq1z9KTQuvgE0rf2I6W}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32678}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
      - API_GROUP={{.Task.Slot}}
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.payroll-{{.Task.Slot}}.rule=Host(`api.karsa.site`) && PathPrefix(`/payroll-{{.Task.Slot}}`)"
        - "traefik.http.routers.payroll-{{.Task.Slot}}.entrypoints=websecure"
        - "traefik.http.routers.payroll-{{.Task.Slot}}.tls.certresolver=myresolver"
        - "traefik.http.services.payroll-{{.Task.Slot}}.loadbalancer.server.port=5003"
        - "traefik.http.routers.payroll-{{.Task.Slot}}.middlewares=payroll-{{.Task.Slot}}-strip"
        - "traefik.http.middlewares.payroll-{{.Task.Slot}}-strip.stripprefix.prefixes=/payroll-{{.Task.Slot}}"
        - "com.centurylinklabs.watchtower.enable=true"
        - "api.group=api-{{.Task.Slot}}"

  gateway:
    image: ghcr.io/aidinaagustin/payroll-mic-gateway:latest
    build:
      context: ./gateway
    environment:
      - PORT=5000
      # Each gateway will need to use service discovery to find its corresponding group services
      - AUTH_SERVICE_URL=http://auth.{{.Task.Slot}}:5001
      - EMPLOYEE_SERVICE_URL=http://employee.{{.Task.Slot}}:5002
      - PAYROLL_SERVICE_URL=http://payroll.{{.Task.Slot}}:5003
      - API_GROUP={{.Task.Slot}}
    depends_on:
      - auth
      - employee
      - payroll
    networks:
      - traefik-public
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway-{{.Task.Slot}}.rule=Host(`api.karsa.site`) && PathPrefix(`/api-{{.Task.Slot}}`)"
        - "traefik.http.routers.gateway-{{.Task.Slot}}.entrypoints=websecure"
        - "traefik.http.routers.gateway-{{.Task.Slot}}.tls.certresolver=myresolver"
        - "traefik.http.services.gateway-{{.Task.Slot}}.loadbalancer.server.port=5000"
        - "traefik.http.routers.gateway-{{.Task.Slot}}.middlewares=gateway-{{.Task.Slot}}-strip"
        - "traefik.http.middlewares.gateway-{{.Task.Slot}}-strip.stripprefix.prefixes=/api-{{.Task.Slot}}"
        - "com.centurylinklabs.watchtower.enable=true"
        - "api.group=api-{{.Task.Slot}}"

networks:
  traefik-public:
    external: true
    name: tascrum_traefik-public