services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  traefik:
    image: "traefik:v3.4"
    ports:
      - mode: host
        published: 81
        target: 81
      # - mode: host
      #   published: 444
      #   target: 444
    networks:
      - microservice-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - traefik-certificates:/letsencrypt
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=microservice-network"
      - "--entrypoints.web.address=:81"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entrypoints.websecure.address=:444"
      # - "--entrypoints.websecure.http.tls=true"
      # - "--entrypoints.websecure.asDefault=true"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=aidinaagustin2@gmail.com"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dashboard.karsa.site`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      # - "traefik.http.routers.traefik.tls=true"
      # - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  auth:
    build:
      context: ./auth
    environment:
      - PORT=5001
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-4P89G57qHVsuMoQXxaK32h1eOUm6iC0I}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32468}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    networks:
      - microservice-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`api.karsa.site`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      # - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=5001"
      - "traefik.http.routers.auth.middlewares=auth-strip"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "com.centurylinklabs.watchtower.enable=true"

  employee:
    build:
      context: ./employee
    environment:
      - PORT=5002
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-4P89G57qHVsuMoQXxaK32h1eOUm6iC0I}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32468}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    depends_on:
      - auth
    networks:
      - microservice-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.employee.rule=Host(`api.karsa.site`) && PathPrefix(`/employee`)"
      - "traefik.http.routers.employee.entrypoints=web"
      # - "traefik.http.routers.employee.tls.certresolver=myresolver"
      - "traefik.http.services.employee.loadbalancer.server.port=5002"
      - "traefik.http.routers.employee.middlewares=employee-strip"
      - "traefik.http.middlewares.employee-strip.stripprefix.prefixes=/employee"
      - "com.centurylinklabs.watchtower.enable=true"

  payroll:
    build:
      context: ./payroll
    environment:
      - PORT=5003
      - DB_HOST=${DB_HOST:-43.133.145.125}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-4P89G57qHVsuMoQXxaK32h1eOUm6iC0I}
      - DB_NAME=${DB_NAME:-hr_payroll_prod}
      - DB_PORT=${DB_PORT:-32468}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_TOKEN=${JWT_TOKEN:-private.pem}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-8}
      - LOG_INFO_FILE_PATH=${LOG_INFO_FILE_PATH:-logs/%DATE%.log}
      - LOG_INFO_MAX_FILE_SIZE=${LOG_INFO_MAX_FILE_SIZE:-20m}
      - LOG_INFO_MAX_FILE_DAY=${LOG_INFO_MAX_FILE_DAY:-1d}
      - LOG_ERROR_FILE_PATH=${LOG_ERROR_FILE_PATH:-logs/app-error-%DATE%.log}
      - LOG_ERROR_MAX_FILE_SIZE=${LOG_ERROR_MAX_FILE_SIZE:-20m}
      - LOG_ERROR_MAX_FILE_DAY=${LOG_ERROR_MAX_FILE_DAY:-1d}
    networks:
      - microservice-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payroll.rule=Host(`api.karsa.site`) && PathPrefix(`/payroll`)"
      - "traefik.http.routers.payroll.entrypoints=web"
      # - "traefik.http.routers.payroll.tls.certresolver=myresolver"
      - "traefik.http.services.payroll.loadbalancer.server.port=5003"
      - "traefik.http.routers.payroll.middlewares=payroll-strip"
      - "traefik.http.middlewares.payroll-strip.stripprefix.prefixes=/payroll"
      - "com.centurylinklabs.watchtower.enable=true"

  gateway:
    build:
      context: ./gateway
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth:5001
      - EMPLOYEE_SERVICE_URL=http://employee:5002
      - PAYROLL_SERVICE_URL=http://payroll:5003
    depends_on:
      - auth
      - employee
      - payroll
    networks:
      - microservice-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.karsa.site`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      # - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.http.services.gateway.loadbalancer.server.port=5000"
      # - "traefik.http.routers.gateway-http.rule=Host(`api.karsa.site`)"
      # - "traefik.http.routers.gateway-http.entrypoints=web"
      # - "traefik.http.routers.gateway-http.middlewares=https-redirect"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  microservice-network:
    driver: bridge

volumes:
  traefik-certificates: