name: Production CI Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push auth service
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          push: true
          tags: ghcr.io/aidinaagustin/payroll-mic-auth:latest

      - name: Build and push employee service
        uses: docker/build-push-action@v5
        with:
          context: ./employee
          push: true
          tags: ghcr.io/aidinaagustin/payroll-mic-employee:latest

      - name: Build and push payroll service
        uses: docker/build-push-action@v5
        with:
          context: ./payroll
          push: true
          tags: ghcr.io/aidinaagustin/payroll-mic-payroll:latest

      - name: Build and push gateway service
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: ghcr.io/aidinaagustin/payroll-mic-gateway:latest

      - name: Create production compose file
        run: |
          sed -i 's/build:/# build:/g' compose-traefik.yaml
          sed -i 's/context:/# context:/g' compose-traefik.yaml

      - name: Copy compose file to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "compose-traefik.yaml"
          target: "/home/${{ secrets.PROD_SSH_USER }}/payroll-mic"

      - name: Stop and remove existing containers
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping and removing existing containers..."
            cd ~/payroll-mic
            docker stack rm payroll-mic || true
            docker system prune -f

      - name: Deploy to VPS
        uses: cssnr/stack-deploy-action@v1
        with:
          name: payroll-mic
          file: compose-traefik.yaml
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          ssh_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          registry_host: 'ghcr.io'
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GHCR_PAT }}
          summary: true