name: Production CI Pipeline

permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --tag ghcr.io/aidinaagustin/payroll-mic:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/aidinaagustin/payroll-mic:latest

      - name: Logout from GitHub Container Registry
        run: docker logout

      - name: Copy compose file to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "compose-traefik.yaml"
          target: "/home/${{ secrets.PROD_SSH_USER }}/payroll-mic"

      - name: Stop and remove existing containers
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping and removing existing containers..."
            cd ~/payroll-mic
            docker stack rm payroll-mic || true
            docker system prune -f

      - name: Deploy to VPS
        uses: cssnr/stack-deploy-action@v1
        with:
          name: payroll-mic
          file: compose-traefik.yaml
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          ssh_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          registry_host: 'ghcr.io'
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GHCR_PAT }}
          summary: true