name: Production CI Pipeline

permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Project Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "auth/,employee/,payroll/,gateway/,compose-traefik.yaml"
          target: "/home/${{ secrets.PROD_SSH_USER }}/microservice-payroll"
          strip_components: 0

      - name: Deploy Stack with Docker Compose
        uses: cssnr/stack-deploy-action@v1
        with:
          name: 'microservice-payroll'
          file: 'compose-traefik.yaml'
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          ssh_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          mode: compose
          args: '--build --force-recreate --remove-orphans'
          summary: true

      - name: Verify Services
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.PROD_SSH_USER }}/microservice-payroll
            
            # Show container status
            echo "Container status:"
            docker ps --format "{{.Names}}: {{.Status}}"
            
            # Verify gateway service is running
            if docker ps | grep -q "microservice-payroll_gateway"; then
              echo "✅ Gateway service is running"
            else
              echo "❌ Gateway service failed to start"
              exit 1
            fi